### ISSUE TITLE
Hi, how to search "special charachters"?

### ISSUE THREAD

**Issue by MichaelRoger** [lucaong/minisearch#121]
hi,
i have a field which contains for example "M/PO-R3".
but how can i find a perfect match using:

let results = miniSearch.search('M/PO-R3');

? Thanks

**Comment by daKmoR** [comment]
@lucaong thank you so much for this detailed explanation 🤗

I didn't run into this use case myself - but I'm now well prepared for it - thanks to you 🤗

**Comment by lucaong** [comment]
Glad it helped @daKmoR !

**Comment by lucaong** [comment]
@MichaelRoger I will close the issue for now, as I think your question is answered, but if you need more information feel free to comment further.

**Comment by MichaelRoger** [comment]
OMG,
i got some errors :-(

```
C:\dev\orgabook\node_modules\minisearch\dist\umd\index.js:747
                tokens.forEach(function (term) {
                       ^

TypeError: tokens.forEach is not a function
    at C:\dev\orgabook\node_modules\minisearch\dist\umd\index.js:747:24
    at Array.forEach (<anonymous>)
    at MiniSearch.add (C:\dev\orgabook\node_modules\minisearch\dist\umd\index.js:740:20)
    at C:\dev\orgabook\node_modules\minisearch\dist\umd\index.js:762:66
    at Array.forEach (<anonymous>)
    at MiniSearch.addAll (C:\dev\orgabook\node_modules\minisearch\dist\umd\index.js:762:23)
    at ServerEngine.handlePeopleFile (C:\dev\orgabook\backendBuild\backend\server.js:202:31)
    at C:\dev\orgabook\backendBuild\backend\server.js:169:31
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)
```
