### ISSUE TITLE
Minisearch crashing

### ISSUE THREAD

**Issue by cmcknight** [lucaong/minisearch#99]
MacOS: 11.5
Node: v15.11.0

Code Example:

```js
const MiniSearch = require('minisearch')

// A collection of documents for our examples
const documents = [
  {
    id: 1,
    title: 'Moby Dick',
    text: 'Call me Ishmael. Some years ago...',
    category: 'fiction'
  },
  {
    id: 2,
    title: 'Zen and the Art of Motorcycle Maintenance',
    text: 'I can see by my watch...',
    category: 'fiction'
  },
  {
    id: 3,
    title: 'Neuromancer',
    text: 'The sky above the port was...',
    category: 'fiction'
  },
  {
    id: 4,
    title: 'Zen and the Art of Archery',
    text: 'At first sight it must seem...',
    category: 'non-fiction'
  },
  // ...and more
]

let miniSearch = new MiniSearch({
  fields: ['title', 'text'], // fields to index for full-text search
  storeFields: ['title', 'category'] // fields to return with search results
})

// Index all documents
miniSearch.addAll(documents)

// Search with default options
let results = miniSearch.search('zen art motorcycle')
```

Error Message:

```
/Volumes/ProjectsDrive/git-projects/layouttest/node_modules/minisearch/dist/umd/index.js:735
                throw new Error("MiniSearch: document does not have ID field \"" + idField + "\"");
                ^

Error: MiniSearch: document does not have ID field "id"
    at MiniSearch.add (/Volumes/ProjectsDrive/git-projects/layouttest/node_modules/minisearch/dist/umd/index.js:735:23)
    at Object.<anonymous> (/Volumes/ProjectsDrive/git-projects/layouttest/searchtest.js:60:12)
```

Removed minisearch from node_modules, re-installed, same error message.

Sort of confusing since it's the sample code from the site demonstrating basic usage.

**Comment by cmcknight** [comment]
And when I do a clean install of everything it works... 🙄
